"use strict";
var items = [
{"ggplotd.aes" : "ggplotd/aes.html"},
{"ggplotd.aes.Pixel" : "ggplotd/aes/Pixel.html"},
{"ggplotd.aes.Pixel.this" : "ggplotd/aes/Pixel.html#this"},
{"ggplotd.aes.Pixel.this" : "ggplotd/aes/Pixel.html#this"},
{"ggplotd.aes.Pixel.value" : "ggplotd/aes/Pixel.html#value"},
{"ggplotd.aes.DefaultValues" : "ggplotd/aes.html#DefaultValues"},
{"ggplotd.aes.Aes" : "ggplotd/aes/Aes.html"},
{"ggplotd.aes.group" : "ggplotd/aes/group.html"},
{"ggplotd.aes.DataID" : "ggplotd/aes/DataID.html"},
{"ggplotd.aes.DataID.this" : "ggplotd/aes/DataID.html#this"},
{"ggplotd.aes.DataID.to" : "ggplotd/aes/DataID.html#to"},
{"ggplotd.aes.DataID.state" : "ggplotd/aes/DataID.html#state"},
{"ggplotd.aes.NumericLabel" : "ggplotd/aes/NumericLabel.html"},
{"ggplotd.aes.NumericLabel.this" : "ggplotd/aes/NumericLabel.html#this"},
{"ggplotd.aes.NumericLabel.front" : "ggplotd/aes/NumericLabel.html#front"},
{"ggplotd.aes.NumericLabel.popFront" : "ggplotd/aes/NumericLabel.html#popFront"},
{"ggplotd.aes.NumericLabel.empty" : "ggplotd/aes/NumericLabel.html#empty"},
{"ggplotd.aes.NumericLabel.save" : "ggplotd/aes/NumericLabel.html#save"},
{"ggplotd.aes.NumericLabel.numeric" : "ggplotd/aes/NumericLabel.html#numeric"},
{"ggplotd.aes.numericLabel" : "ggplotd/aes.html#numericLabel"},
{"ggplotd.aes.merge" : "ggplotd/aes/merge.html"},
{"ggplotd.aes.mergeRange" : "ggplotd/aes.html#mergeRange"},
{"ggplotd.geom" : "ggplotd/geom.html"},
{"ggplotd.geom.Geom" : "ggplotd/geom/Geom.html"},
{"ggplotd.geom.Geom.this" : "ggplotd/geom/Geom.html#this"},
{"ggplotd.geom.Geom.drawFunction" : "ggplotd/geom/Geom.html#drawFunction"},
{"ggplotd.geom.Geom.draw" : "ggplotd/geom/Geom.html#draw"},
{"ggplotd.geom.Geom.colours" : "ggplotd/geom/Geom.html#colours"},
{"ggplotd.geom.Geom.bounds" : "ggplotd/geom/Geom.html#bounds"},
{"ggplotd.geom.Geom.mask" : "ggplotd/geom/Geom.html#mask"},
{"ggplotd.geom.Geom.xTickLabels" : "ggplotd/geom/Geom.html#xTickLabels"},
{"ggplotd.geom.Geom.yTickLabels" : "ggplotd/geom/Geom.html#yTickLabels"},
{"ggplotd.geom.geomShape" : "ggplotd/geom/geomShape.html"},
{"ggplotd.geom.geomType" : "ggplotd/geom/geomType.html"},
{"ggplotd.geom.geomType.geomType" : "ggplotd/geom/geomType.html#geomType"},
{"ggplotd.geom.geomRectangle" : "ggplotd/geom.html#geomRectangle"},
{"ggplotd.geom.geomEllipse" : "ggplotd/geom.html#geomEllipse"},
{"ggplotd.geom.geomTriangle" : "ggplotd/geom.html#geomTriangle"},
{"ggplotd.geom.geomDiamond" : "ggplotd/geom.html#geomDiamond"},
{"ggplotd.geom.geomPoint" : "ggplotd/geom.html#geomPoint"},
{"ggplotd.geom.geomLine" : "ggplotd/geom/geomLine.html"},
{"ggplotd.geom.geomHist" : "ggplotd/geom.html#geomHist"},
{"ggplotd.geom.geomHist2D" : "ggplotd/geom.html#geomHist2D"},
{"ggplotd.geom.geomHist3D" : "ggplotd/geom.html#geomHist3D"},
{"ggplotd.geom.geomAxis" : "ggplotd/geom.html#geomAxis"},
{"ggplotd.geom.geomLabel" : "ggplotd/geom/geomLabel.html"},
{"ggplotd.geom.limits" : "ggplotd/geom.html#limits"},
{"ggplotd.geom.geomBox" : "ggplotd/geom.html#geomBox"},
{"ggplotd.geom.geomPolygon" : "ggplotd/geom.html#geomPolygon"},
{"ggplotd.geom.geomDensity" : "ggplotd/geom.html#geomDensity"},
{"ggplotd.geom.geomDensity2D" : "ggplotd/geom.html#geomDensity2D"},
{"ggplotd.color.xyz" : "ggplotd/color/xyz.html"},
{"ggplotd.color.xyz.WhitePoint" : "ggplotd/color/xyz/WhitePoint.html"},
{"ggplotd.color.xyz.WhitePoint.WhitePoint" : "ggplotd/color/xyz/WhitePoint.WhitePoint.html"},
{"ggplotd.color.xyz.XYZ" : "ggplotd/color/xyz/XYZ.html"},
{"ggplotd.color.xyz.XYZ.ComponentType" : "ggplotd/color/xyz/XYZ.html#ComponentType"},
{"ggplotd.color.xyz.XYZ.X" : "ggplotd/color/xyz/XYZ.html#X"},
{"ggplotd.color.xyz.XYZ.Y" : "ggplotd/color/xyz/XYZ.html#Y"},
{"ggplotd.color.xyz.XYZ.Z" : "ggplotd/color/xyz/XYZ.html#Z"},
{"ggplotd.color.xyz.XYZ.tristimulus" : "ggplotd/color/xyz/XYZ.html#tristimulus"},
{"ggplotd.color.xyz.XYZ.this" : "ggplotd/color/xyz/XYZ.html#this"},
{"ggplotd.color.xyz.xyY" : "ggplotd/color/xyz/xyY.html"},
{"ggplotd.color.xyz.xyY.ComponentType" : "ggplotd/color/xyz/xyY.html#ComponentType"},
{"ggplotd.color.xyz.xyY.x" : "ggplotd/color/xyz/xyY.html#x"},
{"ggplotd.color.xyz.xyY.y" : "ggplotd/color/xyz/xyY.html#y"},
{"ggplotd.color.xyz.xyY.Y" : "ggplotd/color/xyz/xyY.html#Y"},
{"ggplotd.color.xyz.xyY.this" : "ggplotd/color/xyz/xyY.html#this"},
{"ggplotd.color.hsx" : "ggplotd/color/hsx.html"},
{"ggplotd.color.hsx.HSV" : "ggplotd/color/hsx.html#HSV"},
{"ggplotd.color.hsx.HSL" : "ggplotd/color/hsx.html#HSL"},
{"ggplotd.color.hsx.HSI" : "ggplotd/color/hsx.html#HSI"},
{"ggplotd.color.hsx.HCY" : "ggplotd/color/hsx.html#HCY"},
{"ggplotd.color.hsx.HSxType" : "ggplotd/color/hsx/HSxType.html"},
{"ggplotd.color.hsx.HSx" : "ggplotd/color/hsx/HSx.html"},
{"ggplotd.color.hsx.HSx.ComponentType" : "ggplotd/color/hsx/HSx.html#ComponentType"},
{"ggplotd.color.hsx.HSx.colorSpace" : "ggplotd/color/hsx/HSx.html#colorSpace"},
{"ggplotd.color.hsx.HSx.type" : "ggplotd/color/hsx/HSx.html#type"},
{"ggplotd.color.conv" : "ggplotd/color/conv.html"},
{"ggplotd.color.conv.convertColor" : "ggplotd/color/conv.html#convertColor"},
{"ggplotd.color.conv.colorFromString" : "ggplotd/color/conv.html#colorFromString"},
{"ggplotd.color.rgb" : "ggplotd/color/rgb.html"},
{"ggplotd.color.rgb.RGBColorSpace" : "ggplotd/color/rgb/RGBColorSpace.html"},
{"ggplotd.color.rgb.RGB" : "ggplotd/color/rgb/RGB.html"},
{"ggplotd.color.rgb.RGB.ComponentType" : "ggplotd/color/rgb/RGB.html#ComponentType"},
{"ggplotd.color.rgb.RGB.components" : "ggplotd/color/rgb/RGB.html#components"},
{"ggplotd.color.rgb.RGB.colorSpace" : "ggplotd/color/rgb/RGB.html#colorSpace"},
{"ggplotd.color.rgb.RGB.linear" : "ggplotd/color/rgb/RGB.html#linear"},
{"ggplotd.color.rgb.RGB.hasComponent" : "ggplotd/color/rgb/RGB.html#hasComponent"},
{"ggplotd.color.rgb.RGB.hasAlpha" : "ggplotd/color/rgb/RGB.html#hasAlpha"},
{"ggplotd.color.rgb.RGB.tristimulus" : "ggplotd/color/rgb/RGB.html#tristimulus"},
{"ggplotd.color.rgb.RGB.tristimulusWithAlpha" : "ggplotd/color/rgb/RGB.html#tristimulusWithAlpha"},
{"ggplotd.color.rgb.RGB.this" : "ggplotd/color/rgb/RGB.html#this"},
{"ggplotd.color.rgb.RGB.this" : "ggplotd/color/rgb/RGB.html#this"},
{"ggplotd.color.rgb.RGB.this" : "ggplotd/color/rgb/RGB.html#this"},
{"ggplotd.color.rgb.toLinear" : "ggplotd/color/rgb.html#toLinear"},
{"ggplotd.color.rgb.toGamma" : "ggplotd/color/rgb.html#toGamma"},
{"ggplotd.color.rgb.toLinear" : "ggplotd/color/rgb.html#toLinear"},
{"ggplotd.color.rgb.toGamma" : "ggplotd/color/rgb.html#toGamma"},
{"ggplotd.color" : "ggplotd/color.html"},
{"ggplotd.color.RGB8" : "ggplotd/color.html#RGB8"},
{"ggplotd.color.RGBX8" : "ggplotd/color.html#RGBX8"},
{"ggplotd.color.RGBA8" : "ggplotd/color.html#RGBA8"},
{"ggplotd.color.RGBf32" : "ggplotd/color.html#RGBf32"},
{"ggplotd.color.RGBAf32" : "ggplotd/color.html#RGBAf32"},
{"ggplotd.color.BGR8" : "ggplotd/color.html#BGR8"},
{"ggplotd.color.BGRX8" : "ggplotd/color.html#BGRX8"},
{"ggplotd.color.BGRA8" : "ggplotd/color.html#BGRA8"},
{"ggplotd.color.L8" : "ggplotd/color.html#L8"},
{"ggplotd.color.A8" : "ggplotd/color.html#A8"},
{"ggplotd.color.LA8" : "ggplotd/color.html#LA8"},
{"ggplotd.color.UV8" : "ggplotd/color.html#UV8"},
{"ggplotd.color.UVf32" : "ggplotd/color.html#UVf32"},
{"ggplotd.color.Colors" : "ggplotd/color/Colors.html"},
{"ggplotd.axes" : "ggplotd/axes.html"},
{"ggplotd.axes.Axis" : "ggplotd/axes/Axis.html"},
{"ggplotd.axes.Axis.this" : "ggplotd/axes/Axis.html#this"},
{"ggplotd.axes.Axis.label" : "ggplotd/axes/Axis.html#label"},
{"ggplotd.axes.Axis.min" : "ggplotd/axes/Axis.html#min"},
{"ggplotd.axes.Axis.max" : "ggplotd/axes/Axis.html#max"},
{"ggplotd.axes.Axis.min_tick" : "ggplotd/axes/Axis.html#min_tick"},
{"ggplotd.axes.Axis.tick_width" : "ggplotd/axes/Axis.html#tick_width"},
{"ggplotd.axes.Axis.offset" : "ggplotd/axes/Axis.html#offset"},
{"ggplotd.axes.Axis.show" : "ggplotd/axes/Axis.html#show"},
{"ggplotd.axes.XAxis" : "ggplotd/axes/XAxis.html"},
{"ggplotd.axes.XAxis.axis" : "ggplotd/axes/XAxis.html#axis"},
{"ggplotd.axes.YAxis" : "ggplotd/axes/YAxis.html"},
{"ggplotd.axes.YAxis.axis" : "ggplotd/axes/YAxis.html#axis"},
{"ggplotd.axes.initialized" : "ggplotd/axes.html#initialized"},
{"ggplotd.axes.adjustTickWidth" : "ggplotd/axes.html#adjustTickWidth"},
{"ggplotd.axes.axisTicks" : "ggplotd/axes.html#axisTicks"},
{"ggplotd.axes.tickLength" : "ggplotd/axes.html#tickLength"},
{"ggplotd.axes.toAxisLabel" : "ggplotd/axes.html#toAxisLabel"},
{"ggplotd.axes.tickLength" : "ggplotd/axes.html#tickLength"},
{"ggplotd.axes.axisAes" : "ggplotd/axes.html#axisAes"},
{"ggplotd.range" : "ggplotd/range.html"},
{"ggplotd.range.uniquer" : "ggplotd/range.html#uniquer"},
{"ggplotd.range.groupBy" : "ggplotd/range.html#groupBy"},
{"ggplotd.range.mergeRange" : "ggplotd/range.html#mergeRange"},
{"ggplotd.colourspace" : "ggplotd/colourspace.html"},
{"ggplotd.colourspace.toCairoRGBA" : "ggplotd/colourspace.html#toCairoRGBA"},
{"ggplotd.colourspace.fromCairoRGBA" : "ggplotd/colourspace.html#fromCairoRGBA"},
{"ggplotd.colourspace.toTuple" : "ggplotd/colourspace.html#toTuple"},
{"ggplotd.colourspace.toTuple" : "ggplotd/colourspace.html#toTuple"},
{"ggplotd.colourspace.toTuple" : "ggplotd/colourspace.html#toTuple"},
{"ggplotd.ggplotd" : "ggplotd/ggplotd.html"},
{"ggplotd.ggplotd.TitleFunction" : "ggplotd/ggplotd.html#TitleFunction"},
{"ggplotd.ggplotd.Title" : "ggplotd/ggplotd/Title.html"},
{"ggplotd.ggplotd.Title.title" : "ggplotd/ggplotd/Title.html#title"},
{"ggplotd.ggplotd.title" : "ggplotd/ggplotd.html#title"},
{"ggplotd.ggplotd.drawTitle" : "ggplotd/ggplotd.html#drawTitle"},
{"ggplotd.ggplotd.Margins" : "ggplotd/ggplotd/Margins.html"},
{"ggplotd.ggplotd.Margins.this" : "ggplotd/ggplotd/Margins.html#this"},
{"ggplotd.ggplotd.Margins.this" : "ggplotd/ggplotd/Margins.html#this"},
{"ggplotd.ggplotd.Margins.left" : "ggplotd/ggplotd/Margins.html#left"},
{"ggplotd.ggplotd.Margins.right" : "ggplotd/ggplotd/Margins.html#right"},
{"ggplotd.ggplotd.Margins.bottom" : "ggplotd/ggplotd/Margins.html#bottom"},
{"ggplotd.ggplotd.Margins.top" : "ggplotd/ggplotd/Margins.html#top"},
{"ggplotd.ggplotd.GGPlotD" : "ggplotd/ggplotd/GGPlotD.html"},
{"ggplotd.ggplotd.GGPlotD.drawToSurface" : "ggplotd/ggplotd/GGPlotD.html#drawToSurface"},
{"ggplotd.ggplotd.GGPlotD.drawToSurface" : "ggplotd/ggplotd/GGPlotD.html#drawToSurface"},
{"ggplotd.ggplotd.GGPlotD.save" : "ggplotd/ggplotd/GGPlotD.html#save"},
{"ggplotd.ggplotd.GGPlotD.opBinary" : "ggplotd/ggplotd/GGPlotD.html#opBinary"},
{"ggplotd.ggplotd.GGPlotD.put" : "ggplotd/ggplotd/GGPlotD.html#put"},
{"ggplotd.ggplotd.GGPlotD.scale" : "ggplotd/ggplotd/GGPlotD.html#scale"},
{"ggplotd.ggplotd.GGPlotD.colourGradient" : "ggplotd/ggplotd/GGPlotD.html#colourGradient"},
{"ggplotd.ggplotd.Facets" : "ggplotd/ggplotd/Facets.html"},
{"ggplotd.ggplotd.Facets.put" : "ggplotd/ggplotd/Facets.html#put"},
{"ggplotd.ggplotd.Facets.drawToSurface" : "ggplotd/ggplotd/Facets.html#drawToSurface"},
{"ggplotd.ggplotd.Facets.drawToSurface" : "ggplotd/ggplotd/Facets.html#drawToSurface"},
{"ggplotd.ggplotd.Facets.save" : "ggplotd/ggplotd/Facets.html#save"},
{"ggplotd.ggplotd.Facets.save" : "ggplotd/ggplotd/Facets.html#save"},
{"ggplotd.gtk" : "ggplotd/gtk.html"},
{"ggplotd.gtk.GTKWindow" : "ggplotd/gtk/GTKWindow.html"},
{"ggplotd.gtk.GTKWindow.draw" : "ggplotd/gtk/GTKWindow.html#draw"},
{"ggplotd.gtk.GTKWindow.clearWindow" : "ggplotd/gtk/GTKWindow.html#clearWindow"},
{"ggplotd.gtk.GTKWindow.run" : "ggplotd/gtk/GTKWindow.html#run"},
{"ggplotd.bounds" : "ggplotd/bounds.html"},
{"ggplotd.bounds.Point" : "ggplotd/bounds/Point.html"},
{"ggplotd.bounds.Point.x" : "ggplotd/bounds/Point.html#x"},
{"ggplotd.bounds.Point.y" : "ggplotd/bounds/Point.html#y"},
{"ggplotd.bounds.Point.this" : "ggplotd/bounds/Point.html#this"},
{"ggplotd.bounds.Point.this" : "ggplotd/bounds/Point.html#this"},
{"ggplotd.bounds.Point.opEquals" : "ggplotd/bounds/Point.html#opEquals"},
{"ggplotd.bounds.Bounds" : "ggplotd/bounds/Bounds.html"},
{"ggplotd.bounds.Bounds.min_x" : "ggplotd/bounds/Bounds.html#min_x"},
{"ggplotd.bounds.Bounds.max_x" : "ggplotd/bounds/Bounds.html#max_x"},
{"ggplotd.bounds.Bounds.min_y" : "ggplotd/bounds/Bounds.html#min_y"},
{"ggplotd.bounds.Bounds.max_y" : "ggplotd/bounds/Bounds.html#max_y"},
{"ggplotd.bounds.Bounds.this" : "ggplotd/bounds/Bounds.html#this"},
{"ggplotd.bounds.Bounds.this" : "ggplotd/bounds/Bounds.html#this"},
{"ggplotd.bounds.height" : "ggplotd/bounds.html#height"},
{"ggplotd.bounds.width" : "ggplotd/bounds.html#width"},
{"ggplotd.bounds.withinBounds" : "ggplotd/bounds.html#withinBounds"},
{"ggplotd.bounds.validBounds" : "ggplotd/bounds.html#validBounds"},
{"ggplotd.bounds.minimalBounds" : "ggplotd/bounds.html#minimalBounds"},
{"ggplotd.bounds.adjustedBounds" : "ggplotd/bounds.html#adjustedBounds"},
{"ggplotd.bounds.AdaptiveBounds" : "ggplotd/bounds/AdaptiveBounds.html"},
{"ggplotd.bounds.AdaptiveBounds.bounds" : "ggplotd/bounds/AdaptiveBounds.html#bounds"},
{"ggplotd.bounds.AdaptiveBounds.this" : "ggplotd/bounds/AdaptiveBounds.html#this"},
{"ggplotd.bounds.AdaptiveBounds.this" : "ggplotd/bounds/AdaptiveBounds.html#this"},
{"ggplotd.bounds.AdaptiveBounds.this" : "ggplotd/bounds/AdaptiveBounds.html#this"},
{"ggplotd.bounds.AdaptiveBounds.adapt" : "ggplotd/bounds/AdaptiveBounds.html#adapt"},
{"ggplotd.bounds.AdaptiveBounds.adapt" : "ggplotd/bounds/AdaptiveBounds.html#adapt"},
{"ggplotd.bounds.AdaptiveBounds.adapt" : "ggplotd/bounds/AdaptiveBounds.html#adapt"},
{"ggplotd.legend" : "ggplotd/legend.html"},
{"ggplotd.legend.continuousLegend" : "ggplotd/legend.html#continuousLegend"},
{"ggplotd.legend.discreteLegend" : "ggplotd/legend.html#discreteLegend"},
{"ggplotd.legend.drawContinuousLegend" : "ggplotd/legend.html#drawContinuousLegend"},
{"ggplotd.legend.drawDiscreteLegend" : "ggplotd/legend.html#drawDiscreteLegend"},
{"ggplotd.meta" : "ggplotd/meta.html"},
{"ggplotd.meta.ApplyLeft" : "ggplotd/meta.html#ApplyLeft"},
{"ggplotd.stat" : "ggplotd/stat.html"},
{"ggplotd.stat.statFunction" : "ggplotd/stat.html#statFunction"},
{"ggplotd.stat.binID" : "ggplotd/stat.html#binID"},
{"ggplotd.stat.statHist" : "ggplotd/stat.html#statHist"},
{"ggplotd.stat.statHist2D" : "ggplotd/stat.html#statHist2D"},
{"ggplotd.stat.statDensity" : "ggplotd/stat.html#statDensity"},
{"ggplotd.stat.statDensity2D" : "ggplotd/stat.html#statDensity2D"},
{"ggplotd.theme" : "ggplotd/theme.html"},
{"ggplotd.theme.Theme" : "ggplotd/theme/Theme.html"},
{"ggplotd.theme.Theme.backgroundColour" : "ggplotd/theme/Theme.html#backgroundColour"},
{"ggplotd.theme.background" : "ggplotd/theme.html#background"},
{"ggplotd.theme.background" : "ggplotd/theme.html#background"},
{"ggplotd.geometry" : "ggplotd/geometry.html"},
{"ggplotd.geometry.Vertex3D" : "ggplotd/geometry/Vertex3D.html"},
{"ggplotd.geometry.Vertex3D.x" : "ggplotd/geometry/Vertex3D.html#x"},
{"ggplotd.geometry.Vertex3D.y" : "ggplotd/geometry/Vertex3D.html#y"},
{"ggplotd.geometry.Vertex3D.z" : "ggplotd/geometry/Vertex3D.html#z"},
{"ggplotd.geometry.Vertex3D.this" : "ggplotd/geometry/Vertex3D.html#this"},
{"ggplotd.geometry.Vertex3D.this" : "ggplotd/geometry/Vertex3D.html#this"},
{"ggplotd.geometry.Vertex3D.opBinary" : "ggplotd/geometry/Vertex3D.html#opBinary"},
{"ggplotd.geometry.gradientVector" : "ggplotd/geometry.html#gradientVector"},
{"ggplotd.colour" : "ggplotd/colour.html"},
{"ggplotd.colour.createNamedColours" : "ggplotd/colour.html#createNamedColours"},
{"ggplotd.colour.namedColours" : "ggplotd/colour.html#namedColours"},
{"ggplotd.colour.ColourID" : "ggplotd/colour/ColourID.html"},
{"ggplotd.colour.ColourID.this" : "ggplotd/colour/ColourID.html#this"},
{"ggplotd.colour.ColourID.this" : "ggplotd/colour/ColourID.html#this"},
{"ggplotd.colour.ColourID.state" : "ggplotd/colour/ColourID.html#state"},
{"ggplotd.colour.ColourIDRange" : "ggplotd/colour/ColourIDRange.html"},
{"ggplotd.colour.ColourIDRange.this" : "ggplotd/colour/ColourIDRange.html#this"},
{"ggplotd.colour.ColourIDRange.front" : "ggplotd/colour/ColourIDRange.html#front"},
{"ggplotd.colour.ColourIDRange.popFront" : "ggplotd/colour/ColourIDRange.html#popFront"},
{"ggplotd.colour.ColourIDRange.empty" : "ggplotd/colour/ColourIDRange.html#empty"},
{"ggplotd.colour.ColourIDRange.save" : "ggplotd/colour/ColourIDRange.html#save"},
{"ggplotd.colour.ColourMap" : "ggplotd/colour.html#ColourMap"},
{"ggplotd.colour.createColourMap" : "ggplotd/colour.html#createColourMap"},
{"ggplotd.colour.ColourGradientFunction" : "ggplotd/colour.html#ColourGradientFunction"},
{"ggplotd.colour.colourGradient" : "ggplotd/colour.html#colourGradient"},
{"ggplotd.colour.colourGradient" : "ggplotd/colour.html#colourGradient"},
{"ggplotd.algorithm" : "ggplotd/algorithm.html"},
{"ggplotd.algorithm.safeMax" : "ggplotd/algorithm.html#safeMax"},
{"ggplotd.algorithm.safeMin" : "ggplotd/algorithm.html#safeMin"},
{"example" : "example.html"},
{"ggplotd.scale" : "ggplotd/scale.html"},
{"ggplotd.scale.scale" : "ggplotd/scale.html#scale"},
];
function search(str) {
	var re = new RegExp(str.toLowerCase());
	var ret = {};
	for (var i = 0; i < items.length; i++) {
		var k = Object.keys(items[i])[0];
		if (re.test(k.toLowerCase()))
			ret[k] = items[i][k];
	}
	return ret;
}

function searchSubmit(value, event) {
	console.log("searchSubmit");
	var resultTable = document.getElementById("results");
	while (resultTable.firstChild)
		resultTable.removeChild(resultTable.firstChild);
	if (value === "" || event.keyCode == 27) {
		resultTable.style.display = "none";
		return;
	}
	resultTable.style.display = "block";
	var results = search(value);
	var keys = Object.keys(results);
	if (keys.length === 0) {
		var row = resultTable.insertRow();
		var td = document.createElement("td");
		var node = document.createTextNode("No results");
		td.appendChild(node);
		row.appendChild(td);
		return;
	}
	for (var i = 0; i < keys.length; i++) {
		var k = keys[i];
		var v = results[keys[i]];
		var link = document.createElement("a");
		link.href = v;
		link.textContent = k;
		link.attributes.id = "link" + i;
		var row = resultTable.insertRow();
		row.appendChild(link);
	}
}

function hideSearchResults(event) {
	if (event.keyCode != 27)
		return;
	var resultTable = document.getElementById("results");
	while (resultTable.firstChild)
		resultTable.removeChild(resultTable.firstChild);
	resultTable.style.display = "none";
}

